### ISSUE TITLE
localhost issue

### ISSUE THREAD

**Issue by electropolis** [AlexGluck/ZBX_NGINX#5]
https://github.com/AlexGluck/ZBX_NGINX/blob/097a2c7d379ac54285c811ebc631d4d4e750827f/Template_App_Nginx.xml#L469

I would prefer to change **NGINX_HOST** from **localhost** to universal **127.0.0.1**

For example I had issue with that and receive when checking with **zabbix_get** this

> $ zabbix_get -s nginx-node -I 172.31.255.254 -k web.page.get[localhost,nginx_status,80]
> ZBX_NOTSUPPORTED: HTTP get error: cannot connect to [[localhost]:80]: [111] Connection refused

Which was strange because **curl** worked

> $ curl -Is http://localhost/nginx_status
> HTTP/1.1 200 OK
> Server: nginx
> Date: Wed, 01 Aug 2018 14:55:51 GMT
> Content-Type: text/plain
> Connection: keep-alive

> $ curl http://localhost/nginx_status
> Active connections: 1
> server accepts handled requests
>  34 34 35
> Reading: 0 Writing: 1 Waiting: 0

So I started to check what is behined **localhost** and here was the reason why it won't work

> $ ping localhost
> PING localhost(localhost (::1)) 56 data bytes
> 64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.017 ms
> 64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.036 ms

and 

> $ cat /etc/hosts
> 127.0.0.1	localhost
> ::1		localhost ip6-localhost ip6-loopback

So after hashing second line **(::1)**

> $ ping localhost
> PING localhost (127.0.0.1) 56(84) bytes of data.
> 64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.016 ms
> 64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.033 ms

and 

> $ zabbix_get -s nginx-node -I 172.31.255.254 -k web.page.get[localhost,nginx_status,80]
> HTTP/1.1 200 OK
> Server: nginx
> Date: Wed, 01 Aug 2018 15:29:36 GMT
> Content-Type: text/plain
> Content-Length: 100
> Connection: close
> 
> Active connections: 1
> server accepts handled requests
>  40 40 41
> Reading: 0 Writing: 1 Waiting: 0

  
The reason for that is **NGINX_HOST: localhost**

**Comment by AlexGluck** [comment]
Fix in commit. Thx
https://github.com/AlexGluck/ZBX_NGINX/commit/0ad45e26dc804adc21dc8137391d808bc7cdfdd3
